### ISSUE TITLE
Live ECMWF India

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nwp-consumer#102]
Deploy live NWP for ECMWF India. 

We are currently waiting on ECMWF to start sending us data. It will be put in the S3 bucket XXXX (on production). TODO need to see if this data is here yet.
- The Nwp-consumer should then take this data (probably grib files) and save the data in the OCF foremat, (zarr.zip)
- Becasue only one lot of data is being sent, we need to think how to share the data with the dev enviornment. I think there are some s3 sync options that we could do

**Comment by devsjc** [comment]
Waiting on ECMWF to get back in touch with details about the delivery.

**Comment by peterdudfield** [comment]
might need this - https://repost.aws/knowledge-center/datasync-transfer-cross-account-s3

**Comment by peterdudfield** [comment]
https://docs.aws.amazon.com/datasync/latest/userguide/tutorial_s3-s3-cross-account-transfer.html

**Comment by peterdudfield** [comment]
It might be easier to give access the nwp-consumer access to this bucket,  using https://stackoverflow.com/questions/77637011/how-to-provide-access-to-s3-buckets-in-a-different-aws-account

**Comment by peterdudfield** [comment]
https://repost.aws/knowledge-center/cross-account-access-s3

**Comment by peterdudfield** [comment]
Another potential method would be to pass through aws credietnials so that nwp can read the new bucket. This might be simplier and less fiddler than creating extra roles e.t.c
