### ISSUE TITLE
Fix integration tests

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nwp-consumer#116]
## Detailed Description
Fix integration tests

## Context
- might be due to upgrade for nwp-consumer

## Possible Implementation
add metoffice api key to repo secrets?
might be some other stuff too

**Comment by peterdudfield** [comment]
Need to add `METOFFICE_API_KEY`

**Comment by devsjc** [comment]
https://github.com/openclimatefix/nwp-consumer/commit/d793fac394b882141b5490da8ad89771b660e188

**Comment by devsjc** [comment]
Closed with https://github.com/openclimatefix/nwp-consumer/pull/137
