### ISSUE TITLE
load from s3 bucket

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nwp-consumer#120]
## Detailed Description
Update nwp-consumer for ECMWF data. This will load grib files straight from s3 bucket. The s3 bucket is only on production environment, so will did to give credientails to access that

## Context
#103 #104 

## Possible Implementation
- Load the most recent data
- join together and save
- probably a new one here - https://github.com/openclimatefix/nwp-consumer/tree/main/src/nwp_consumer/internal/inputs, might be able to build of ecmwf

**Comment by devsjc** [comment]
Yes, since the aim is to read ECMWF data I'd be tempted to have a new file within the `ecmwf` adaptor e.g. `s3.py` that performs this.

**Comment by devsjc** [comment]
Files are now present in bucket - see [https://github.com/openclimatefix/nwp-consumer/issues/103#issuecomment-1957297314](https://github.com/openclimatefix/nwp-consumer/issues/103#issuecomment-1957297314) for initial investigation into file contents.

**Comment by devsjc** [comment]
Quick fix to consumer for reading the files [6469ed2](https://github.com/openclimatefix/nwp-consumer/commit/6469ed2dfc553c0d552d614fded99d4802dc4ec8)

**Comment by devsjc** [comment]
Also see: https://github.com/openclimatefix/ocf-infrastructure/pull/458
