### ISSUE TITLE
renam t2m to t

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nwp-consumer#127]
## Detailed Description
Could `t2m` be renamed to `t`, the ML models expects it to be t and I think its the same thing. 

## Context
running Windnet for the first time with this data

## Possible Implementation
change it here https://github.com/openclimatefix/nwp-consumer/blob/main/src/nwp_consumer/internal/inputs/ecmwf/s3.py#L27

**Comment by devsjc** [comment]
I'd rather the change was made to the OCFShortName Enum for temperature, since its those enums that try to enable us to keep consistent names across providers.

**Comment by peterdudfield** [comment]
Ah ok, Ill leave it how it is, and do the change somewhere else. Then its all standard here

**Comment by devsjc** [comment]
I'd expect this block to be carrying out that exact rename https://github.com/openclimatefix/nwp-consumer/blob/5fb39ac822ac35900cb0887eb4259bf7d3059544/src/nwp_consumer/internal/inputs/ecmwf/s3.py#L142-L146

**Comment by devsjc** [comment]
See https://github.com/openclimatefix/nwp-consumer/pull/128

**Comment by devsjc** [comment]
Where are you seeing this? I've downloaded `latest.zarr.zip` from both the india an uk buckets, and examined the variable coordinate and they both are as follows:
```
['clt' 'dlwrf' 'dswrf' 'duvrs' 'hcc' 'lcc' 'mcc' 'prate' 'sde' 'sr' 't'
 'u10' 'u100' 'u200' 'v10' 'v100' 'v200' 'vis']
```
i.e. `t`, not `t2m` is not present.
