### ISSUE TITLE
Get TCC from ECMWF

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nwp-consumer#131]
## Detailed Description
Add TCC variable to the Live India ECMWF order

## Context
- needed for Windnet India - https://github.com/openclimatefix/india-forecast-app/issues/31

## Possible Implementation
- ask ECMWF?

**Comment by devsjc** [comment]
`tcc` is already being pulled from ECMWF, but the consumer renames it to `clt` as that is what is outlined as used for `Total Cloud Cover` in the internal OCFShortName enum - and as such what I considered to be the desired name for consistency. See https://github.com/openclimatefix/nwp-consumer/blob/819b63db153b1f8dd537a5a7571d0aa2ec128154/src/nwp_consumer/internal/inputs/ecmwf/s3.py#L24 and https://github.com/openclimatefix/nwp-consumer/blob/819b63db153b1f8dd537a5a7571d0aa2ec128154/src/nwp_consumer/internal/inputs/ecmwf/s3.py#L145-L147 and https://github.com/openclimatefix/nwp-consumer/blob/819b63db153b1f8dd537a5a7571d0aa2ec128154/src/nwp_consumer/internal/models.py#L19

Should I change the internal naming to favour `tcc` instead?

**Comment by peterdudfield** [comment]
I think this is now done?
