### ISSUE TITLE
Meteomatics Live Service

### ISSUE THREAD

**Issue by devsjc** [openclimatefix/nwp-consumer#142]
For the RUVNL long range forecast live service, Meteomatics needs to be incorporated into the NWP consumer in order for a live service to be created. This will also require some admin work with Meteomatics setting up a contract.

**Comment by devsjc** [comment]
See https://github.com/openclimatefix/ocf-infrastructure/pull/538 for deploying to development

**Comment by peterdudfield** [comment]
Ill close this for the moment. Paused as we couldnt find the difference meteomatics made
