### ISSUE TITLE
Speed up docker

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nwp-consumer#15]
Currently the build and pushing the docker file can take ~20. We got round this using github action cache. The tricky thing is installing eccodes. 

We might be able to use [this](https://github.com/openclimatefix/MetOfficeDataHub/blob/main/infrastructure/docker/Dockerfile) from the old nwp consumer and adapt it and it might be quicker

Steps could be 
1. Build current file locally, see how long it takes
2. Check the image can run python file, might not fully work as you dont have secret nwp values
3. re work docker image, and test it works ok

**Comment by devsjc** [comment]
It seems to me like the docker build-and-push action is not caching layers between different branches? This could account for some of the slow builds.

**Comment by devsjc** [comment]
However the latest tag build only took 3 minutes which is in line with the other consumer so perhaps removing the ARM image is enough optimizing for now.
