### ISSUE TITLE
vairable changes name 0.5.5 to 0.5.13 and some zeros?

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nwp-consumer#156]
## Detailed Description
The variables seems to hange name from 0.5.5 to 0.5.13

## Context
- forecast goes wrong, and we think it was due to nwp change

### Old (from 4th June)
- ukv: ['dlwrf', 'dswrf', 'hcc', 'lcc', 'mcc', 'prate', 'r', 'sde', 'si10',
       't', 'vis', 'wdir10']
ecmwf: ['tcc', 'dlwrf', 'dswrf', 'duvrs', 'hcc', 'lcc', 'mcc', 'prate',
       'sde', 'sr', 't', 'u10', 'u100', 'u200', 'v10', 'v100', 'v200',
       'vis'] 
### New

- UKV: ['r', 't', 'vis', 'wdir10', 'si10', 'hcc', 'lcc', 'mcc', 'dlwrf',
       'dswrf', 'prate', 'sde']
- ECMWF: ['sr', 'duvrs', 'sde', 'clt', 'u10', 'v10', 't', 'dswrf', 'dlwrf',
       'lcc', 'mcc', 'hcc', 'vis', 'u200', 'v200', 'u100', 'v100',
       'prate'] 

## Possible Implementation
- work out why this is happened? 
- either update NWP-consumer, or update pvnet_app to rename
- or update ocf_datapipes

**Comment by peterdudfield** [comment]
tcc seems to be missing from ECMWF in the new one, and possibly renamed as clt?

**Comment by peterdudfield** [comment]
Could be fixed once this is done - https://github.com/openclimatefix/ocf_datapipes/issues/326

Also could be fixed in pvnet_app - https://github.com/openclimatefix/pvnet_app/blob/main/pvnet_app/data.py#L267

**Comment by Sukh-P** [comment]
Mentioned this to @devsjc earlier today and I am not sure but [these logs](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/$252Faws$252Fecs$252Fconsumer$252Fnwp-consumer-ecmwf-uk/log-events/streaming$252Fnwp-consumer-ecmwf-uk-consumer$252F7403a0dd8d904ea58319305d3b191f51$3FfilterPattern$3D) look suspicious as they mention renamed variables and says something like "filling missing variables with 0" and has an exception so could be related to that issue

**Comment by peterdudfield** [comment]
I think this is all done now
