### ISSUE TITLE
Only build docker for linux

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nwp-consumer#17]
## Detailed Description
Currently we build for linux and arm in the CI. I think we should just build for linux. If we want arm image, this can be done locally

## Context
- CI is taking a long time, good to reduce it
- CI might reduce with #15

## Possible Implementation
change code in ci.yaml - https://github.com/openclimatefix/nwp-consumer/blob/main/.github/workflows/ci.yml#L149

**Comment by Marsh-sudo** [comment]
@peterdudfield so you want to create separate job that builds a docker image for linux 🤔

**Comment by peterdudfield** [comment]
Hi @Marsh-sudo - thanks for getting in contact

Currently it builds both linux and mac docker images 'platforms: linux/amd64,linux/arm64`, see link above. Could you reduce this to just `linux`. This will be a very small change, but #15 will be something you can get your teeth into
