### ISSUE TITLE
latest file disappares for a long time

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nwp-consumer#175]
With have noticed PVnet failing a few times due to 

FileNotFoundError: ['nowcasting-nwp-development/ecmwf/data/latest.zarr']
<img width="643" alt="Screenshot 2024-09-25 at 16 37 35" src="https://github.com/user-attachments/assets/a3b1fa88-ee00-45d1-a211-4e08d9f16244">

Just want to double check, that when switch to the new latest.zarr file we do this really quickly. Like
1. save latest_new.zarr
2. rename latest.zarr to latest_old.zarr
3. rename latest_new.zarr to latest.zarr

This might be quicker than delteting and then saving

**Comment by peterdudfield** [comment]
I think the code is here - https://github.com/openclimatefix/nwp-consumer/blob/main/src/nwp_consumer/internal/service/consumer.py#L143

**Comment by devsjc** [comment]
Yes, you'd probably have to add a `move` or a `rename` function to the [storage interface](https://github.com/openclimatefix/nwp-consumer/blob/main/src/nwp_consumer/internal/models.py#L147), then add an implementation in the S3 and local storage adaptors, and then update the logic there to go from `delete -> create new` to `create new with name latest-temp -> delete latest -> rename latest.temp to latest` or something similar.

**Comment by peterdudfield** [comment]
This could be related to #176

**Comment by peterdudfield** [comment]
Looks like it is solved in 0.5.28
