### ISSUE TITLE
fix unit tests

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nwp-consumer#180]
![Screenshot 2024-10-01 at 09 45 12](https://github.com/user-attachments/assets/96723c2a-a6a0-40ed-879b-f20a21e6f5d6)

This current stops a release being made

**Comment by devsjc** [comment]
Time for the ever-present line - the tests both run fine on my machine! Not sure what is going on here, especially as these tests were passing the other day and no one has touched them...

**Comment by peterdudfield** [comment]
Ill close this for the moment
