### ISSUE TITLE
0.5.27

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nwp-consumer#185]
https://github.com/openclimatefix/pv-site-production/issues/91

Pv-site-production didnt seem to work tieh 0.5.27, but was fine with 0.5.25. Im not sure what the issue is to be honest

**Comment by peterdudfield** [comment]
Nor does pvnet

**Comment by peterdudfield** [comment]
I this could be related to the variables not be renamed proberly

<img width="606" alt="Screenshot 2024-10-04 at 14 38 43" src="https://github.com/user-attachments/assets/8dce28d5-3e3f-41aa-a7d4-3f1f6572e6a6">

**Comment by peterdudfield** [comment]
Could be good idea to pin requirements to make sure this doesnt happy

**Comment by devsjc** [comment]
I'll see if I can pin down whether its something that has changed in the `cfgrib` or `eccodes` library, as they are what decode the grib messages - I can't think of any changes in the repository itself that would lead to this otherwise, that test file and the reading code hasn't been touched in a long time! If so, as you say, an explicit version pin should resolve it.

**Comment by peterdudfield** [comment]
Was the idea to pin the requirments, similar to your local to check it works ok?

**Comment by devsjc** [comment]
It was, see https://github.com/openclimatefix/nwp-consumer/pull/186

**Comment by peterdudfield** [comment]
Sorry im still seeing issues with 0.5.27

**Comment by peterdudfield** [comment]
Im just trying to run the docker file made on `main` to see if we have the same issue

**Comment by peterdudfield** [comment]
started a draft PR - https://github.com/openclimatefix/nwp-consumer/pull/187

**Comment by peterdudfield** [comment]
Annoying thing is the test works fine locally, but doesnt work in the CI and docker file e.t.c. 

i might try builind the nwp docker file locally, and run the test in that

**Comment by peterdudfield** [comment]
could be related to https://github.com/ecmwf/cfgrib/issues/385?

**Comment by peterdudfield** [comment]
Looks like it is solved in 0.5.28
