### ISSUE TITLE
ECMWF Full Ensemble small archive

### ISSUE THREAD

**Issue by devsjc** [openclimatefix/nwp-consumer#193]
For WP6, we require an initial small archive of ECMWF ensemble data (1 week).

To be determined:
- [x] Dimensions
- [x] Ensemble Members
- [x] Existance of useable archive

**Comment by devsjc** [comment]
I'm assuming for this work, since we're just comparing against our current output, and this is for NG, we will want data for the same dimensions as best as is possible for our current UK dataset.

**Comment by devsjc** [comment]
[This paper](https://www.researchgate.net/publication/365404135_An_archived_dataset_from_the_ECMWF_Ensemble_Prediction_System_for_probabilistic_solar_power_forecasting#pf10) details an acessible 4 year archive (2017-2020) of ensemble data. It only contains the `dswrf` or `ssrd` parameter, but it argues it's the most important one and the others don't differ much between ensembles anyway. An example dataset from a file of the data is as follows:

```
<xarray.Dataset> Size: 1GB
Dimensions:    (longitude: 325, latitude: 85, number: 50, time: 91)
Coordinates:
  * longitude  (longitude) float32 1kB -126.0 -125.5 -125.0 ... 35.0 35.5 36.0
  * latitude   (latitude) float32 340B 63.0 62.5 62.0 61.5 ... 22.0 21.5 21.0
  * number     (number) int32 200B 1 2 3 4 5 6 7 8 9 ... 43 44 45 46 47 48 49 50
  * time       (time) datetime64[ns] 728B 2020-12-31 ... 2021-01-03T18:00:00
Data variables:
    ssrd       (time, number, latitude, longitude) float64 1GB ...
Attributes:
    Conventions:  CF-1.6
    history:      2021-11-15 18:06:04 GMT by grib_to_netcdf-2.23.0: grib_to_n...
```
The latitude/longitude covers the UK, and it has 50 members. @peterdudfield Would this be useful/good enough for our purposes to kick off WP6?

**Comment by peterdudfield** [comment]
I would of thought so, it would be good to test this out and play with ti. Even if its just trying ti with a small amount of data

**Comment by devsjc** [comment]
Downloading to `/mnt/storage_c/ephemeral/ecmwf-eps-wp6`.

**Comment by devsjc** [comment]
One month downloaded to the above path which quantifies as a "small archive", so I'm closing the ticket.
