### ISSUE TITLE
Load `AWS_ACCESS_KEY` and `AWS_ACCESS_KEY` from env

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nwp-consumer#20]
## Detailed Description
Would be nice not to have to enter the following variables as env environmental variables.
Would be nice if this ere load from the default values. On AWS this means that the IAM role is loaded

## Context
- trying to deploy new nwp-consumer,, and it works when setting these values
- nice to set these values, for secruity concerns

## Possible Implementation
something in https://github.com/openclimatefix/nwp-consumer/blob/main/src/nwp_consumer/internal/config/config.py?

**Comment by peterdudfield** [comment]
The change could also be in `outputs/se/clients.py`

**Comment by peterdudfield** [comment]
we might be able to just remove `key` and `secret` if they are set to none from 
```
      self.__fs: s3fs.S3FileSystem = s3fs.S3FileSystem(
            key=key,
            secret=secret,
            client_kwargs={
                'region_name': region,
                'endpoint_url': endpointURL,
            }
        )
```
and then the IAM role is loaded

**Comment by peterdudfield** [comment]
this should do it, I tried it locally
```
        if (key == '') or (secret == ''):
            self.__fs: s3fs.S3FileSystem = s3fs.S3FileSystem(
                key=key,
                secret=secret,
                client_kwargs={
                    'region_name': region,
                    'endpoint_url': endpointURL,
                }
            )
        else:
            self.__fs: s3fs.S3FileSystem = s3fs.S3FileSystem(
                client_kwargs={
                    'region_name': region,
                    'endpoint_url': endpointURL,
                }
            )
```

@devsjc what do you think?

**Comment by devsjc** [comment]
I'd be happy making the behaviour tree as the following:
1. look for env vars, use them if set
2. if not set, look for default values and use them if available
3. if neither of those work, error

I'd argue this order since default values are exactly that (default) and so should be possible to be overridden by the env vars. If I'm understanding you correctly this is what you're suggesting as well.

A couple of questions though:
> nice to set these values, for secruity concerns

I'd argue env vars are a very secure way to pass sensitive info into an application, and it plays by the rules of a 12 factor app, so I'm not sure I know what you mean here? 

```python
if (key == '') or (secret == ''):
      self.__fs: s3fs.S3FileSystem = s3fs.S3FileSystem(
          key=key,
          secret=secret,
          client_kwargs={
              'region_name': region,
              'endpoint_url': endpointURL,
          }
   )
```
shoiuld they not be `!=` in the `if`?

**Comment by peterdudfield** [comment]
> if (key == '') or (secret == ''):
>             self.__fs: s3fs.S3FileSystem = s3fs.S3FileSystem(
>                 key=key,
>                 secret=secret,
>                 client_kwargs={
>                     'region_name': region,
>                     'endpoint_url': endpointURL,
>                 }
>             )
>         else:
>             self.__fs: s3fs.S3FileSystem = s3fs.S3FileSystem(
>                 client_kwargs={
>                     'region_name': region,
>                     'endpoint_url': endpointURL,
>                 }
>             )

yea sorry it should be `!=` and perhaps `and` not `or`.

I agree with 1. .2 and 3. Just the default values here are `None`, so im not sure how that fits in? 

It's perhaps more secure not to put AWS secrets in the ECS task definition, as if someone gets that task definition they can then use stuff. Instead the behaviour seems to be dont set that, but use the default values from the IAM role assgined to that task definition.
