### ISSUE TITLE
Dont upload to s3 if not changed

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nwp-consumer#30]
## Detailed Description
I think at the moment, every run of nwp-consumer saves to s3, even if there is no new data

## Context
- https://github.com/openclimatefix/PVNet/issues/83, not sure if this is the reason though

## Possible Implementation
- check size of file in s3, if the same, don upload?

**Comment by devsjc** [comment]
From memory it shouldn't do - what is it that is suggesting to you that it is at the moment?

**Comment by peterdudfield** [comment]
I was looking at the logs, and each time the nwp-consumer runs, it looks like it uploads a new `latest` file? 

If it does, is it worth checking the exact size of the file, and if its the same, then dont upload

**Comment by devsjc** [comment]
Are you sure checking the size is an adequate comparison? Considering the data will all be of the same primitive types and should have the same number of values, might it not be the case that two subsequent datasets could have the same size with different data?

**Comment by peterdudfield** [comment]
It could be, is there a hash or something or the data that would be better to use. 

Maybe this isnt the right solution, just seems a bit odd, if the data is exactly the same in s3, that we reload it

**Comment by jacobbieker** [comment]
With compression, if the data is laid out differently, it could still have a different size, so going off the size might still work? More time-intensive, but could open the metadata and read the timestamps of the remote and local ones and see if they match?

**Comment by peterdudfield** [comment]
Yea, checking time stamps of the s3 file is probably the safest way to go. Hopefully dont have to open the whole file, can just load a bit of it

**Comment by peterdudfield** [comment]
I wonder if a simplier way would be to have an option to only create latest file if there are new raw files

**Comment by devsjc** [comment]
Fixed with #195
