### ISSUE TITLE
Add nans check

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nwp-consumer#62]
## Detailed Description
- Could we add a check (which logs a warning) if there are any nans in the data

## Context
- good to flag this?
- Q: should this raise an assertion instead? 

## Possible Implementation
Once all data is downloaded we check for
- nans
- all values are the same
- could look at each channel / variable

**Comment by devsjc** [comment]
There already is! https://github.com/openclimatefix/nwp-consumer/blob/a7bd3515606950bf9f505d1ca64c81c339458d92/src/nwp_consumer/internal/service/service.py#L340

**Comment by peterdudfield** [comment]
ohh nice
